version: '3.8'

services:
  webwand:
    image: htetlinmaung/webwand
    restart: always
    ports:
      - "8005:3000"
    environment:
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
    volumes:
      - ./images:/app/images
      - ./pdf:/app/pdf
